# Generated by Django 4.2.3 on 2023-10-30 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_postal_code_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('temperament', models.CharField(choices=[('C', 'Choleryk'), ('S', 'Sangwinik'), ('F', 'Flegmatyk'), ('M', 'Melancholik')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SmartTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperament', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
