# Generated by Django 4.2.3 on 2023-11-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_smarttestanswer_smarttestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogPersonalityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('temperament', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DogPersonaltyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('domain', models.CharField(choices=[('Ekstrawersja/Introwersja', 'Ekstrawersja/Introwersja'), ('Neurotyzm', 'Neurotyzm'), ('Otwartość na nowe doświadczenia', 'Otwartość na nowe doświadczenia'), ('Ugodowość', 'Ugodowość')], max_length=255)),
                ('answer', models.CharField(choices=[('1', 'Tak'), ('0', 'Nie')], max_length=1)),
            ],
        ),
    ]
