# Generated by Django 4.2.3 on 2023-11-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dogpersonaltyquestion_answer_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogpersonaltyquestion',
            old_name='text',
            new_name='question_text',
        ),
        migrations.AlterUniqueTogether(
            name='smarttestresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dogpersonalityresult',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dogpersonaltyquestion',
            name='question_number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
