# Generated by Django 4.2.3 on 2024-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_prescreeninganswer_prescreeningquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('User', 'User'), ('Volunteer', 'Volunteer'), ('Administrator', 'Administrator')], max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
