# .black

[tool.black]
line-length = 88
target-version = ['py38']
exclude = '''
/(
  \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.black.prerun]
skip-string-normalization = true
